### ISSUE TITLE
Getting NPE while using ProxyResults

### ISSUE THREAD

**Issue by GoldenGamerLP** [DefianceCoding/ProxyCheckJavaAPIV2#1]
**Describe the bug**
Im getting a NullPointerException when using your Libary. The NullPointerExeception seems to come from your Libary and not my Application.

**To Reproduce**
1. Using the latest version of your Libary.
2. Using getAndMapresults(String ip);
3. Getting the error.

**Expected behavior**
There shouldnt be a NPE. It should give the ProxyResults class back.

**Screenshots**
![image](https://user-images.githubusercontent.com/65727384/139688564-69c1f596-a9d2-450b-93e8-7d0ab3b532cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Java: 15
 - Version: Latest

**Comment by DefianceCoding** [comment]
Hello,
Sorry you seem to be having issues, may I ask for the code you are using, as the tests I ran show the right results https://prnt.sc/1y2oboh

**Comment by GoldenGamerLP** [comment]
Ah okay, in youre example, youre not using the ProxyCheckSettings, maybe thats my issue?


My code:
`java
public class ProxyCheckListener implements ModuleImpl, SimpleCommand {

    private DatabaseManager databaseManager;
    private VeloUtilities veloUtilities;
    private final ProxyCheck proxyCheck = new ProxyCheck();
    private final ProxyCheckSettings settings = new ProxyCheckSettings();

    @Override
    public String load(VeloUtilities veloUtilities) {
        this.databaseManager = veloUtilities.getDatabaseManager();
        this.veloUtilities = veloUtilities;

        settings.setApi_key("my-key-for-the-api");
        settings.setCheck_vpn(true);
        settings.setCheck_asn(true);
        settings.setCheck_node(true);
        settings.setCheck_time(true);
        settings.setRiskLevel(1);
        settings.setCheck_port(true);
        settings.setCheck_seen(true);
        settings.setMax_detection_days(1);
        settings.setVer("Ver");
        settings.setTag("ProxyCheckJavaAPI");

        veloUtilities.getServer().getEventManager().register(veloUtilities, this);
        return "ProxyCheck";
    }

    @Override
    public String unload(VeloUtilities veloUtilities) {
        veloUtilities.getServer().getEventManager().unregisterListener(veloUtilities, this);
        return "ProxyCheck";
    }


    @Override
    public void execute(Invocation invocation) {
        String[] args = invocation.arguments();
        CommandSource commandSource = invocation.source();
        Player player = commandSource instanceof Player player1 ? player1 : null;


    }

    @Subscribe(order = PostOrder.LAST, async = true)
    public void onConnect(ServerPreConnectEvent serverPreConnectEvent) throws SQLException {
        Player player = serverPreConnectEvent.getPlayer();
        if (!serverPreConnectEvent.getResult().isAllowed()) return;
        ProxyResults proxyResults = checkCompletableFuture(player.getRemoteAddress().getAddress().getHostAddress()).join();
        boolean isInDatabase = databaseManager.hasEntry(player.getUniqueId()).join();
        if (!proxyResults.getStatus().equals("ok") && !isInDatabase)
            player.disconnect(Component.text("An error occoured with the proxycheck!"));
        if (!databaseManager.hasConnection().join()) player.disconnect(Component.text("No connection to database!"));

        int riskScore = Integer.parseInt(proxyResults.getRisk());
        boolean isSafe = Stream.of("residential", "wireless", "business", "hosting").anyMatch(s -> s.equals(proxyResults.getType()));
        if (riskScore <= 66 && isSafe || riskScore <= 33) {
            databaseManager.savePlayerInDatabase(new ProxyEntry(player.getUniqueId(), System.currentTimeMillis(), riskScore)).join();
            player.sendMessage(Component.text("Nice!"));
        } else player.disconnect(Component.text(String.format("Riskcore: %d || isSafe = %s", riskScore, isSafe)));
    }`
